	<script src="<?=site_url("assets/libs/jquery-1.12.4.min.js")?>"></script>
	<script src="<?=site_url("assets/libs/jquery-migrate-1.2.1.js")?>"></script>
	<script src="<?=site_url("assets/libs/bootstrap/bootstrap.min.js")?>"></script>
	<script src="<?=site_url("assets/plugins/slabText/js/jquery.slabtext.min.js")?>"></script>
	<script src="<?=site_url("assets/plugins/owl-carousel/owl.carousel.min.js")?>"></script>
	<script src="<?=site_url("assets/plugins/slick/slick.min.js")?>"></script>
	<script src="<?=site_url("assets/plugins/slyslider/sly.min.js")?>"></script>
	<script src="<?=site_url("assets/plugins/bxslider/vendor/jquery.easing.1.3.js")?>"></script>
	<script src="<?=site_url("assets/plugins/bxslider/vendor/jquery.fitvids.js")?>"></script>
	<script src="<?=site_url("assets/plugins/bxslider/jquery.bxslider.min.js")?>"></script>
	<script src="<?=site_url("assets/plugins/magnific-popup/jquery.magnific-popup.min.js")?>"></script>
	<script src="<?=site_url("assets/plugins/headers/slidebar.js")?>"></script>
	<script src="<?=site_url("assets/plugins/headers/header.js")?>"></script>
	<script src="<?=site_url("assets/plugins/isotope/isotope.pkgd.min.js")?>"></script>
	<script src="<?=site_url("assets/plugins/isotope/imagesLoaded.js")?>"></script>
	<script src="<?=site_url("assets/plugins/rendro-easy-pie-chart/jquery.easypiechart.min.js")?>"></script>
	<script src="<?=site_url("assets/plugins/rendro-easy-pie-chart/waypoints.min.js")?>"></script>
	<script src="<?=site_url("assets/plugins/wow.min.js")?>"></script>
	<script src="<?=site_url("assets/plugins/pickmeup/pickmeup.js")?>"></script>
	<script src="<?=site_url("assets/js/custom.js")?>"></script>
	<script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyBqQ_bBw186KJnMcRByvn5ffZueg88wp1E"></script>
	<script src="<?=site_url("assets/js/custom-map.js")?>"></script>
	<script src="<?=site_url("assets/plugins/jqBootstrapValidation.js")?>"></script>
	<script src="<?=site_url("assets/plugins/contact_me.js")?>"></script>
	<script src="<?=site_url("assets/js/contactformcheck.js")?>"></script>